### PR TITLE
Please fix asap

### PR DESCRIPTION
**Pull request by louisstow**

### CODE REVIEW

**Comment by lamberta** [comment]
Shoulda fixed this and we wouldn't need https://github.com/mikehenrty/icebreak-preso/pull/1

**Comment by mikehenrty** [comment]
@lamberta , sorry I missed your message here. This repo is deprecated in favor of https://github.com/fairfieldt/thin-pdo-wrapper, which itself was deprecated in favor of https://github.com/louisstow/thin-pdo-wrapper, so please file all future concerns there. Thanks for being a part of this vibrant community!

**Comment by louisstow** [comment]
@lamberta @mikehenrty @CarlQLange I would like to propose a merging of thin PDO wrappers and the creation of the Open Thin PDO Wrapper spec with ourselves as the consortium.

**Comment by mikehenrty** [comment]
@louisstow this is how we get rich

image

**Comment by lamberta** [comment]
@mikehenrty Understandable, GitHub is simultaneously the worst social platform ever and the only way to keep up with @CarlQLange . 

I second @louisstow's proposal for the creation of the Open Thin PDO Wrapper Consortium. In light of recent comments regarding financial motivation, as member-elect I move to immediately assign all copyright to the [Khronos Group](https://www.khronos.org/).

**Comment by louisstow** [comment]
Seconded. The OTPDOW logo, branding and all related copyright shall henceforth be given to Lord Khronos.

**Pull request closed without merging**
